### ISSUE TITLE
Implementing ccmdesign changes

### ISSUE THREAD

**Issue by drkane** [ThreeSixtyGiving/Insights#44]
From: https://github.com/ccmdesign/360-insights

## Need advice/new styling from @ccmdesign:

- [x] Loading screen
- [ ] Fetch data modal (#52)
   - [ ] general design
   - [ ] progress bar (x2)
   - [ ] Button for when file has been fetched
- [x] Upload data button - needs current styles applied to default dash module
- [x] Chart styling #79
- [x] Filters - what to do when there's a long list
- [x] Multi-select dropdowns
- [x] Styling of subheaders & description next to charts #79
- [x] Map styling #79
- [x] Footer on chart page #56 
- [x] Select a new dataset #66
- [x] years filter #71 

## To-do by @drkane:

- [x] Implement date range dash component - https://github.com/ThreeSixtyGiving/Insights/commit/530a543c20f42d7064b8125f7a67bf2bab2cb344
- [x] Blue stats bubble needs shorter numbers in the £1,000 - £1,000,000 range (use `k` suffix)
- [x] Make newsletter sign-up work
